### In this notebook we will perform some EDA to explore the data

Import the modules

In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go

Load the data

In [5]:
df = pd.read_csv('data/CSV/Alzheimer_final.csv')
df.head()

           ID       Age  Gender  Educ      MMSE  Target      eTIV      nWBV
0  011_S_0003  0.717371       1   4.0  0.081752     1.0  0.014743  0.223724
1  022_S_0004 -0.854411       1   0.0  0.836511     1.0  0.014743  0.223724
2  011_S_0005 -0.148249       1   3.0  1.052156     0.0  0.014743  0.223724
3  100_S_0006  0.614863       0   2.0  0.620865     1.0  0.014743  0.223724
4  011_S_0010 -0.125469       0   1.0  0.513043     1.0  0.014743  0.223724

In [7]:
eda_df = df.drop(['ID'], axis=1)
eda_df.head()

        Age  Gender  Educ      MMSE  Target      eTIV      nWBV
0  0.717371       1   4.0  0.081752     1.0  0.014743  0.223724
1 -0.854411       1   0.0  0.836511     1.0  0.014743  0.223724
2 -0.148249       1   3.0  1.052156     0.0  0.014743  0.223724
3  0.614863       0   2.0  0.620865     1.0  0.014743  0.223724
4 -0.125469       0   1.0  0.513043     1.0  0.014743  0.223724

Show the target labels -  We figure out that there is no unbalncing data in the target labels

In [11]:
eda_df['Target'].value_counts()

Target
0.0    1920
1.0    1458
Name: count, dtype: int64

### Graph-1 generate boxplots map to show the overlaps between features and target

In [12]:
features = ['Age', 'Educ', 'MMSE', 'eTIV', 'nWBV']

In [ ]:
df_melted = df.melt(id_vars=['Target'], value_vars=features, 
                    var_name='Feature', value_name='Scaled Value')
df_melted['Target'] = df_melted['Target'].map({0.0: '0 (Healthy)', 1.0: '1 (Early-Stage)'}) # To make the legend is more readaple

In [15]:
fig = px.box(df_melted, 
             x='Target', 
             y='Scaled Value', 
             color='Target', 
             facet_col='Feature', 
             facet_col_wrap=3, # Creates the 2x3 grid automatically
             title='Interactive Distribution of Features by Diagnosis',
             color_discrete_sequence=px.colors.qualitative.Set2)

fig.for_each_annotation(lambda a: a.update(text=a.text.split("=")[-1]))
fig.update_yaxes(matches=None)
fig.show()

This figure shows that data is overlaped across Educatin and Age

This figure shows a small diffrence in the MMSE score and this will be our golden feature

There are many extreme outliers in eTIV and nWBV

### Graph-2 show the correlation map between features

In [19]:
corr_matrix = eda_df.corr().round(2)
fig = go.Figure(data=go.Heatmap(
                   z=corr_matrix.values, # The actual correlation numbers
                   x=corr_matrix.columns, # The X-axis labels
                   y=corr_matrix.columns, # The Y-axis labels
                   colorscale='RdBu_r',   # Red-Blue scale (similar to coolwarm)
                   zmin=-1,               # Set minimum color scale to -1
                   zmax=1,                # Set maximum color scale to 1
                   text=corr_matrix.values, # Put the numbers inside the squares
                   texttemplate="%{text}",  # Format the text to display correctly
                   hoverinfo="x+y+z"      # Show X, Y, and Value when hovering
               ))

# 5. Clean up the Layout for Professional Presentation
fig.update_layout(
    title='Interactive Feature Correlation Heatmap',
    title_x=0.5, # Center the title
    width=800,
    height=800,
    xaxis_showgrid=False,
    yaxis_showgrid=False,
    yaxis_autorange='reversed' # Flips the Y-axis so the diagonal goes top-left to bottom-right
)


fig.show()

No multicollinearity detected

Low linear target correlation is expected as biology is not in linear form